import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testajensiacloud.carifer.com/login');
  await page.getByRole('textbox', { name: 'Username *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Password *' }).fill('Admin@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: ' Employee Management 󰅂' }).click();
  await page.getByRole('link', { name: 'Employee', exact: true }).click();
  await page.getByRole('button', { name: 'Add Employee' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Test');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Employee');
  await page.getByRole('textbox', { name: 'Mobile Number*' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number*' }).fill('8776656233');
  await page.getByRole('textbox', { name: 'Alternative Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Alternative Mobile Number' }).fill('8767676766');
  await page.getByRole('textbox', { name: 'Emergency Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Emergency Mobile Number' }).fill('7676734344');
  await page.getByRole('textbox', { name: 'Relation (Emergency Contact' }).click();
  await page.getByRole('textbox', { name: 'Relation (Emergency Contact' }).fill('Manoj');
  await page.getByRole('textbox', { name: 'Personal Email*' }).click();
  await page.getByRole('textbox', { name: 'Personal Email*' }).fill('mana@gmail.com');
  await page.getByRole('textbox', { name: 'PAN Number*' }).click();
  await page.getByRole('textbox', { name: 'PAN Number*' }).fill('GRGSS7672637');
  await page.getByRole('textbox', { name: 'UAN Number' }).click();
  await page.getByRole('textbox', { name: 'UAN Number' }).fill('726367367333');
  await page.getByRole('textbox', { name: 'Aadhaar Card Number*' }).click();
  await page.getByRole('textbox', { name: 'Aadhaar Card Number*' }).fill('123223213321');
  await page.getByRole('textbox', { name: 'Passport Number' }).click();
  await page.getByRole('textbox', { name: 'Passport Number' }).fill('E8787287');
  await page.getByRole('textbox', { name: 'Date Of Issue' }).fill('2025-02-25');
  await page.getByRole('textbox', { name: 'Valid Upto' }).fill('2035-09-05');
  await page.getByRole('textbox', { name: 'Date Of Birth*' }).fill('2003-01-01');
  await page.getByLabel('Martial Status').selectOption('Married');
  await page.getByLabel('Blood Group').selectOption('B+');
  await page.getByLabel('Gender*').selectOption('Male');
  await page.getByLabel('Nationality').selectOption('76');
  await page.getByLabel('Country').selectOption('6');
  await page.getByLabel('State', { exact: true }).selectOption('489');
  await page.getByText('City select').click();
  await page.getByLabel('City', { exact: true }).selectOption('3');
  await page.getByRole('textbox', { name: 'Current Address*' }).click();
  await page.getByRole('textbox', { name: 'Current Address*' }).fill('Test');
  await page.getByRole('textbox', { name: 'Permanent Address*' }).click();
  await page.getByRole('textbox', { name: 'Permanent Address*' }).fill('Test');
  await page.getByRole('textbox', { name: 'Postal Code' }).click();
  await page.getByRole('textbox', { name: 'Postal Code' }).fill('7676376');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('textbox', { name: 'Name of Dependent' }).click();
  await page.getByRole('textbox', { name: 'Name of Dependent' }).fill('Test');
  await page.getByRole('textbox', { name: 'Relationship to Employee' }).click();
  await page.getByRole('textbox', { name: 'Relationship to Employee' }).fill('Test');
  await page.getByRole('button', { name: ' Next' }).click();
  await page.pause();
  

});