name: Playwright Tests
 
on:
 push:
   #branches: [master]
    paths:
      - 'tests/Ajensia/Approvals/**'

 pull_request:
  # branches: [master]
 paths:
      - 'tests/Ajensia/Approvals/**'
 
jobs:
 run-playwright-tests:
   runs-on: ubuntu-latest
 
   steps:
     - name: Checkout repo
       uses: actions/checkout@v3
 
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18
 
     - name: Install dependencies
       run: npm ci
 
     - name: Install Playwright browsers
       run: npx playwright install --with-deps
 
     - name: Run Playwright tests
       run: npm test
 
     # ⛔️ Temporarily disabled due to "Missing download info" error
     # - name: Upload Playwright HTML Report
     #   if: always()
     #   uses: actions/upload-artifact@v2
     #   with:
     #     name: playwright-html-report
     #     path: playwright-report/